In [138]:
import numpy as np
from desdeo_mcdm.interactive.NautilusNavigator import NautilusNavigator
# from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(suppress=True)

In [139]:
#-return, risk, -esg
F = np.load("./data/F.npy")

# scaler = MinMaxScaler()
# Fn = scaler.fit_transform(F)

ideal = np.min(F, axis=0)
nadir = np.max(F, axis=0)

method = NautilusNavigator(F, ideal, nadir)

req = method.start()
print(req)
print(req.content.keys())
print(req.content["message"])
print(req.content["reachable_lb"])
print(req.content["reachable_ub"])


dict_keys(['message', 'ideal', 'nadir', 'reachable_lb', 'reachable_ub', 'user_bounds', 'reachable_idx', 'step_number', 'steps_remaining', 'distance', 'allowed_speeds', 'current_speed', 'navigation_point'])
Please supply aspirations levels for each objective between the upper and lower bounds as `reference_point`. Specify a speed between 1-5 as `speed`. If going to a previous step is desired, please set `go_to_previous` to True, otherwise it should be False. Bounds for one or more objectives may also be specified as 'user_bounds'; when navigating,the value of the objectives present in the navigation points will not exceed the valuesspecified in 'user_bounds'.Lastly, if stopping is desired, `stop` should be True, otherwise it should be set to False.
[-0.0429  0.0049 -9.9915]
[ 0.0006  0.0242 -6.6809]


In [140]:
response = {
    "reference_point": np.array([-0.03, 0.015, -8]),
    "go_to_previous": False,
    "stop": False,
    "speed": 1,
    "user_bounds": nadir
}

while method._step_number < 60:
    req.response = response
    req = method.iterate(req)

print(req.content["reachable_lb"])
print(req.content["reachable_ub"])
print(req.content["reachable_idx"])

[-0.0406  0.0059 -9.9534]
[ 0.0006  0.0198 -6.6809]
[  0   2   6   8   9  10  11  13  15  16  20  22  23  24  26  29  30  32
  33  34  36  37  38  39  41  42  43  46  47  48  50  51  52  53  54  56
  57  58  61  63  64  65  66  69  70  72  73  74  75  77  78  79  80  82
  84  85  86  89  90  91  92  94  95  96  97  98  99 100 101 102 103 104
 106 108 109 110 114 116 117 118 120 121 122 123 124 125 126 127 129 130
 131 132 133 136 137 138 140 141 142 144 145 146 149 150 151 152 153 154
 156 157 159 160 161 162 163 164 166 167 169 170 171 172 173 175 176 178
 179 180 181 182 184 185 186 189 190 191 193 194 195 196 198 199]


In [141]:
response["reference_point"] = np.array([-0.035, 0.01, -8])

while method._step_number < 80:
    req.response = response
    req = method.iterate(req)

print(req.content["reachable_lb"])
print(req.content["reachable_ub"])
print(req.content["reachable_idx"])

[-0.0378  0.0075 -9.2452]
[-0.0081  0.0153 -6.6809]
[  2   9  10  13  15  29  30  32  37  42  51  57  66  74  75  90  95  96
  99 102 114 121 122 126 133 140 142 145 150 152 154 157 159 162 166 167
 173 178 179 180 182 185 191 193 195]


In [142]:
response["reference_point"] = np.array([-0.035, 0.009, -8])

while method._step_number < 100:
    req.response = response
    req = method.iterate(req)

print(req.content["reachable_lb"])
print(req.content["reachable_ub"])
print(req.content["reachable_idx"])

[-0.0317  0.0092 -8.6752]
[-0.0317  0.0092 -8.6752]
154
